# Generated by Django 2.2 on 2021-10-12 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XBT_PW',
            new_name='BTC_PW',
        ),
    ]
